project_id = "nlpnfkidnixphnlwhrux"

[functions.google-calendar-events]
verify_jwt = true

[functions.google-oauth-callback]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.chatwoot-webhook]
verify_jwt = false

[functions.send-evolution-message]
verify_jwt = false

[functions.evolution-webhook]
verify_jwt = false
